packages:
  - examples/*

minimumReleaseAgeExclude:
  - '@rspack/*'
  - '@rsbuild/*'
  - '@rslib/*'
  - '@rstest/*'
  - '@rslint/*'
  - '@typescript/*'
  - typescript
  - '@rstackjs/test-utils@0.2.0'
